--Yeongyu Library Complete Database Schema
-- Version: 1.3 (Auto-Generated by GitHub Copilot)
-- Date: 2026-01-25
-- Description: 包含所有建表、权限、索引优化及预设数据的完整脚本

--------------------------------------------------------------------------------
-- 1. 基础配置 (Extensions & Enums)
--------------------------------------------------------------------------------

-- 启用 UUID 生成扩展
create extension if not exists "uuid-ossp";
-- 启用 pg_trgm 扩展 (用于高性能模糊搜索)
create extension if not exists "pg_trgm";

-- 定义用户角色枚举
create type user_role as enum ('user', 'admin');


--------------------------------------------------------------------------------
-- 2. 表结构定义 (Tables)
--------------------------------------------------------------------------------

-- 2.1 邀请码表 (用于注册验证)
create table public.invite_codes (
  id uuid default gen_random_uuid() primary key,
  code text not null unique,       -- 邀请码
  email text not null unique,      -- 绑定邮箱
  is_used boolean default false,   -- 是否已使用
  created_at timestamptz default now()
);

-- 2.2 用户信息表 (扩展 Supabase auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  role user_role default 'user',   -- 默认为认证用户
  avatar_url text,
  created_at timestamptz default now()
);

-- 2.3 标签定义表
create table public.tags (
  id bigint generated by default as identity primary key,
  category text not null, -- 分类：'类型', '情感', '剧情', '人设' 等
  name text not null,     -- 标签名：'同人文', '甜文', '破镜重圆' 等
  unique (category, name) -- 防止重复标签
);

-- 2.4 作品主表
create table public.works (
  id bigint generated by default as identity primary key,
  title text not null,
  author_name text not null,
  original_url text not null, -- 原文链接
  platform text not null,     -- 发布平台 (Lofter, AO3, etc.)
  summary text,               -- 简介
  submitter_id uuid references public.profiles(id), -- 谁提交的
  created_at timestamptz default now(),
  constraint unique_work_url unique (original_url)
);

-- 2.5 作品-标签 关联表 (多对多)
create table public.work_tags (
  work_id bigint references public.works(id) on delete cascade,
  tag_id bigint references public.tags(id) on delete cascade,
  primary key (work_id, tag_id)
);

-- 2.6 收藏夹文件夹
create table public.favorite_folders (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null, -- 文件夹名字
  created_at timestamptz default now()
);

-- 2.7 收藏夹-作品 关联表
create table public.folder_entries (
  folder_id bigint references public.favorite_folders(id) on delete cascade,
  work_id bigint references public.works(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (folder_id, work_id)
);

-- 2.8 树洞留言表 (Radio)
create table public.radio_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  nickname text not null, -- 自定义留言人名称
  content text not null,  -- 留言内容
  linked_work_id bigint references public.works(id), -- 可选：引用的作品ID
  created_at timestamptz default now()
);

-- 2.9 留言表情表态表 (Reactions)
create table public.radio_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint references public.radio_messages(id) on delete cascade,
  user_id uuid references public.profiles(id) not null,
  emoji text not null, -- 存 emoji 字符
  created_at timestamptz default now(),
  unique (message_id, user_id, emoji)
);


--------------------------------------------------------------------------------
-- 3. 核心函数与触发器 (Functions & Triggers)
--------------------------------------------------------------------------------

-- 3.1 自动同步 Profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, new.raw_user_meta_data->>'username', 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3.2 标记邀请码已使用 (安全函数)
create or replace function mark_invite_used(invite_id uuid)
returns void
language plpgsql
security definer -- 以管理员权限运行，绕过RLS
as $$
begin
  update public.invite_codes
  set is_used = true
  where id = invite_id;
end;
$$;


--------------------------------------------------------------------------------
-- 4. 性能索引优化 (Indexes)
--------------------------------------------------------------------------------

-- 4.1 搜索优化 (pg_trgm)
create index if not exists idx_works_title_trgm on works using gin (title gin_trgm_ops);
create index if not exists idx_works_author_trgm on works using gin (author_name gin_trgm_ops);

-- 4.2 标签关联查询优化 (高频JOIN)
create index if not exists idx_work_tags_tag_id on work_tags(tag_id);
create index if not exists idx_work_tags_work_id on work_tags(work_id);
create index if not exists idx_tags_category on tags(category);

-- 4.3 电台查询优化 (时间倒序 & 用户相关)
create index if not exists idx_radio_created_at on radio_messages(created_at desc);
create index if not exists idx_radio_reactions_message_id on radio_reactions(message_id);
create index if not exists idx_radio_reactions_user_id on radio_reactions(user_id);

-- 4.4 收藏夹查询优化
create index if not exists idx_favorite_folders_user_id on favorite_folders(user_id);
create index if not exists idx_folder_entries_work_id on folder_entries(work_id);
create index if not exists idx_folder_entries_folder_id on folder_entries(folder_id);


--------------------------------------------------------------------------------
-- 5. 安全策略 (RLS Policies)
--------------------------------------------------------------------------------

-- 启用 RLS
alter table invite_codes enable row level security;
alter table profiles enable row level security;
alter table works enable row level security;
alter table tags enable row level security;
alter table work_tags enable row level security;
alter table radio_messages enable row level security;
alter table radio_reactions enable row level security; -- 补上这个漏网之鱼
alter table favorite_folders enable row level security;
alter table folder_entries enable row level security; -- 补上这个漏网之鱼

-- 5.1 Invite Codes 策略
create policy "Allow public read invite codes" on invite_codes for select using (true);

-- 5.2 Profiles 策略
create policy "Profiles are public" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- 5.3 Works 策略
create policy "Works are public" on works for select using (true);
create policy "Users can insert works" on works for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update works" on works for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
-- 允许作者删除自己的作品 (逻辑保留，按需调整)
create policy "Users can delete own works" on works for delete using (auth.uid() = submitter_id);

-- 5.4 Tags 策略
create policy "Public read tags" on tags for select using (true);
create policy "Authenticated insert tags" on tags for insert with check (auth.role() = 'authenticated');

-- 5.5 Work Tags 策略
create policy "Public read work_tags" on work_tags for select using (true);
create policy "Authenticated insert work_tags" on work_tags for insert with check (auth.role() = 'authenticated');
create policy "Authenticated delete work_tags" on work_tags for delete using (auth.role() = 'authenticated');

-- 5.6 Radio 策略
create policy "Messages are public" on radio_messages for select using (true);
create policy "Users can insert messages" on radio_messages for insert with check (auth.role() = 'authenticated');

-- 5.7 Reactions 策略
create policy "Reactions are public" on radio_reactions for select using (true);
create policy "Users can insert reactions" on radio_reactions for insert with check (auth.role() = 'authenticated');
create policy "Users can delete own reactions" on radio_reactions for delete using (auth.uid() = user_id);

-- 5.8 Favorites 策略 (隐私保护：仅自己可见)
create policy "Users can see own favorites" on favorite_folders for select using (auth.uid() = user_id);
create policy "Users can manage own favorites" on favorite_folders for all using (auth.uid() = user_id);

create policy "Users can see own folder entries" on folder_entries for select using (
  exists (select 1 from favorite_folders where id = folder_id and user_id = auth.uid())
);
create policy "Users can manage own folder entries" on folder_entries for all using (
  exists (select 1 from favorite_folders where id = folder_id and user_id = auth.uid())
);


--------------------------------------------------------------------------------
-- 6. 初始化数据 (Seeds)
--------------------------------------------------------------------------------
insert into public.tags (category, name) values
-- 作品类型
('类型', '同人文'), ('类型', '捡手机'), ('类型', '论坛体'), ('类型', '视频剪辑'), ('类型', '条漫/漫画'),
-- 大标签
('世界观', '现实背景向'), ('世界观', '架空现代'), ('世界观', '架空幻想'), ('世界观', '架空古代'),
-- 篇幅
('篇幅', '短打'), ('篇幅', '短篇'), ('篇幅', '中篇'), ('篇幅', '长篇'),
-- 进度
('进度', '连载中'), ('进度', '已完结'),
-- 情感基调
('情感', '甜文'), ('情感', '虐文'), ('情感', '酸甜'), ('情感', '搞笑'), ('情感', '正剧'), ('情感', '暗黑'),
-- 提示
('预警', 'BE'), ('预警', 'OE'), ('预警', 'R18'), ('预警', '主要角色死亡'), ('预警', '非双洁'), ('预警', 'SM'), ('预警', '性转'),
-- 剧情定位
('剧情', '破镜重圆'), ('剧情', '竹马竹马'), ('剧情', '校园'), ('剧情', '娱乐圈'), ('剧情', '公司职场'), 
('剧情', '先婚后爱'), ('剧情', '穿越'), ('剧情', '宫廷'), ('剧情', '江湖'), ('剧情', '仙侠'),
-- 常见人设
('人设', '黑帮'), ('人设', '杀手'), ('人设', '站街'), ('人设', '网簧'), ('人设', '有生理/心理疾病'),
-- 特殊设定
('设定', 'HP设定'), ('设定', 'abo设定'), ('设定', 'cake&fork设定'), ('设定', '哨向设定'), ('设定', '赛博朋克'),
-- 幻想设定
('幻想', '花吐症'), ('幻想', '机器人/仿生人'), ('幻想', '末日'), ('幻想', '幽灵/鬼魂/妖精'), ('幻想', '天使恶魔'), 
('幻想', '吸血鬼'), ('幻想', '小动物'), ('幻想', '人鱼')
on conflict (category, name) do nothing; -- 防止重复插入报错
