-- Yeongyu Library: 注册系统升级 - 邀请码 → 糖点答题
-- Version: 2.0
-- Date: 2026-05-25
-- Description: 新增题库表和已验证邮箱表，弃用邀请码表

--------------------------------------------------------------------------------
-- 1. 新表创建
--------------------------------------------------------------------------------

-- 1.1 题库表
create table public.quiz_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null check (correct_option in ('a', 'b', 'c', 'd')),
  created_at timestamptz default now()
);

-- 1.2 已验证邮箱表（替代 invite_codes）
create table public.verified_emails (
  id uuid default gen_random_uuid() primary key,
  email text not null unique,
  score integer not null,
  is_used boolean default false,
  created_at timestamptz default now()
);

--------------------------------------------------------------------------------
-- 2. 安全函数（SECURITY DEFINER，绕过 RLS）
--------------------------------------------------------------------------------

-- 2.1 随机获取题目（不含正确答案）
create or replace function public.get_random_questions(limit_count integer)
returns table(
  id bigint,
  question text,
  option_a text,
  option_b text,
  option_c text,
  option_d text
)
language plpgsql
security definer
as $$
begin
  return query
  select q.id, q.question, q.option_a, q.option_b, q.option_c, q.option_d
  from public.quiz_questions q
  order by random()
  limit limit_count;
end;
$$;

-- 2.2 批改答案并返回分数
-- answer_data 格式: [{"id": 1, "answer": "a"}, {"id": 2, "answer": "c"}, ...]
create or replace function public.check_quiz_answers(answer_data json)
returns table(total integer, correct integer, score integer)
language plpgsql
security definer
as $$
declare
  ans record;
  correct_count integer := 0;
  total_count integer := 0;
  correct_opt char(1);
begin
  for ans in select * from json_to_recordset(answer_data) as (id bigint, answer text)
  loop
    total_count := total_count + 1;
    select q.correct_option into correct_opt
    from public.quiz_questions q
    where q.id = ans.id;
    if correct_opt is not null and correct_opt = ans.answer then
      correct_count := correct_count + 1;
    end if;
  end loop;

  return query
  select
    total_count,
    correct_count,
    case when total_count > 0
      then (correct_count * 100 / total_count)
      else 0
    end;
end;
$$;

-- 2.3 查询已验证邮箱（注册时校验用）
create or replace function public.check_verified_email(email_addr text)
returns table(
  id uuid,
  email text,
  score integer,
  is_used boolean,
  created_at timestamptz
)
language plpgsql
security definer
as $$
begin
  return query
  select v.id, v.email, v.score, v.is_used, v.created_at
  from public.verified_emails v
  where v.email = email_addr
    and v.is_used = false
  limit 1;
end;
$$;

-- 2.4 记录/更新已验证邮箱（答题通过时调用）
create or replace function public.upsert_verified_email(email_addr text, quiz_score integer)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.verified_emails (email, score, is_used)
  values (email_addr, quiz_score, false)
  on conflict (email) do update set score = quiz_score, is_used = false;
end;
$$;

-- 2.5 标记邮箱已使用（注册时调用）
create or replace function public.mark_email_used(email_addr text)
returns void
language plpgsql
security definer
as $$
begin
  update public.verified_emails
  set is_used = true
  where email = email_addr;
end;
$$;

--------------------------------------------------------------------------------
-- 3. RLS 策略
--------------------------------------------------------------------------------

alter table quiz_questions enable row level security;
alter table verified_emails enable row level security;

-- 题库：不允许公开直接查询（只能通过安全函数访问）
-- 不创建任何 select policy，所有访问走 SECURITY DEFINER 函数

-- 已验证邮箱：不允许公开直接查询（只能通过安全函数访问）
-- 不创建任何 select/insert/update policy，所有访问走 SECURITY DEFINER 函数

--------------------------------------------------------------------------------
-- 4. 数据迁移：将未使用的邀请码邮箱迁移到新表
--------------------------------------------------------------------------------

insert into public.verified_emails (email, score, is_used, created_at)
select email, -1, false, created_at
from public.invite_codes
where is_used = false
on conflict (email) do nothing;

-- 迁移完成后可删除旧表（手动执行）
-- drop table if exists public.invite_codes;
-- drop function if exists public.mark_invite_used(uuid);

--------------------------------------------------------------------------------
-- 5. 索引
--------------------------------------------------------------------------------

create index if not exists idx_verified_emails_email on verified_emails(email);
create index if not exists idx_quiz_questions_created_at on quiz_questions(created_at);
